import http from 'node:http';
import fs from 'node:fs/promises';
import path from 'node:path';
import crypto from 'node:crypto';
import {fileURLToPath} from 'node:url';
import sharp from 'sharp';
import ffmpegPath from 'ffmpeg-static';
import {spawn} from 'node:child_process';

const ROOT=path.dirname(path.dirname(fileURLToPath(import.meta.url)));
const PUBLIC=path.join(ROOT,'generated');
const DB=path.join(ROOT,'server','data','credits.json');
const PORT=Number(process.env.PORT||8787), FREE=8, MAX=4, MAXBODY=60*1024*1024;
const MODEL='minimax/video-01';
let lock=Promise.resolve();
const serial=fn=>{const n=lock.then(fn,fn);lock=n.catch(()=>{});return n;};
const today=()=>new Date().toISOString().slice(0,10);
async function db(){try{return JSON.parse(await fs.readFile(DB,'utf8'));}catch{return{users:{},jobs:{}};}}
async function save(x){await fs.mkdir(path.dirname(DB),{recursive:true});await fs.writeFile(DB,JSON.stringify(x,null,2));}
function wallet(d,id){const t=today(),w=d.users[id]||{plan:'free',credits:FREE,refreshedAt:t};if(w.refreshedAt!==t){w.credits=w.plan==='pro'?Number(process.env.PRO_DAILY_CREDITS||100):FREE;w.refreshedAt=t;}d.users[id]=w;return w;}
function send(r,s,b,type='application/json; charset=utf-8'){r.writeHead(s,{'content-type':type,'access-control-allow-origin':'*','access-control-allow-headers':'content-type,x-client-id','access-control-allow-methods':'GET,POST,OPTIONS'});r.end(type.startsWith('application/json')?JSON.stringify(b):b);}
const cid=r=>r.headers['x-client-id']||r.socket.remoteAddress||'anonymous';
async function body(r){const a=[];let n=0;for await(const c of r){n+=c.length;if(n>MAXBODY)throw Error('Upload is too large.');a.push(c);}return Buffer.concat(a);}
function multipart(b,ct){const m=ct.match(/boundary=(?:"([^"]+)"|([^;]+))/),bd=m?.[1]||m?.[2];if(!bd)return{fields:{},files:[]};const fields={},files=[];for(const p of b.toString('binary').split(`--${bd}`).slice(1,-1)){const[h,x='']=p.replace(/^\r\n/,'').split('\r\n\r\n'),name=h.match(/name="([^"]+)"/)?.[1],fn=h.match(/filename="([^"]*)"/)?.[1];if(!name)continue;const v=x.replace(/\r\n$/,'');if(fn)files.push({filename:fn,mime:h.match(/Content-Type:\s*([^\r\n]+)/i)?.[1]||'image/jpeg',buffer:Buffer.from(v,'binary')});else fields[name]=Buffer.from(v,'binary').toString();}return{fields,files:files.filter(f=>f.mime.startsWith('image/')).slice(0,MAX)};}
const uri=(b,m='image/jpeg')=>`data:${m};base64,${b.toString('base64')}`;
async function replicate(input){if(!process.env.REPLICATE_API_TOKEN)throw Error('REPLICATE_API_TOKEN is required.');const r=await fetch(`https://api.replicate.com/v1/models/${MODEL}/predictions`,{method:'POST',headers:{Authorization:`Bearer ${process.env.REPLICATE_API_TOKEN}`,'Content-Type':'application/json'},body:JSON.stringify({input})});const d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.detail||d.error||`Replicate error ${r.status}`);return d;}
async function poll(id){const r=await fetch(`https://api.replicate.com/v1/predictions/${encodeURIComponent(id)}`,{headers:{Authorization:`Bearer ${process.env.REPLICATE_API_TOKEN}`}});const d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.detail||d.error||`Poll error ${r.status}`);return d;}
async function download(url,file){const r=await fetch(url);if(!r.ok)throw Error(`Could not download generated shot (${r.status}).`);await fs.writeFile(file,Buffer.from(await r.arrayBuffer()));}
function outputUrl(p){return Array.isArray(p.output)?p.output[0]:p.output;}
function runFfmpeg(files,out){return new Promise((resolve,reject)=>{const list=path.join(path.dirname(out),`concat-${crypto.randomUUID()}.txt`);fs.writeFile(list,files.map(f=>`file '${f.replace(/'/g,"'\\''")}'`).join('\n')).then(()=>{const p=spawn(ffmpegPath,['-y','-f','concat','-safe','0','-i',list,'-c','copy',out]);let err='';p.stderr.on('data',x=>err+=x);p.on('close',async code=>{await fs.rm(list,{force:true});code===0?resolve():reject(Error(err.slice(-1200)||'FFmpeg merge failed.'));});}).catch(reject);});}
function enhance(p,d,a){return `${p}. Create a coherent ${d}-second cinematic shot from this reference image. Smooth natural camera motion, realistic subject motion, preserve identity and anatomy, stable lighting and background, temporal consistency, premium color grade, no flicker, no warping, no duplicate subjects, no text.`;}
async function runJob(id){const d=await db(),j=d.jobs[id];if(!j)return;j.status='generating';j.progress=8;await save(d);const shots=[];try{for(let i=0;i<j.images.length;i++){const img=j.images[i];j.shot=i+1;j.progress=10+Math.floor((i/j.images.length)*70);await save(d);const prediction=await replicate({prompt:enhance(j.prompt,j.shotDuration,j.aspect),duration:j.shotDuration,aspect_ratio:j.aspect,negative_prompt:j.negative,image:uri(Buffer.from(img.data,'base64'),img.mime)});j.providerIds.push(prediction.id);await save(d);let p=prediction;let waited=0;while(!['succeeded','failed','canceled'].includes(p.status)){await new Promise(r=>setTimeout(r,2500));waited+=2.5;if(waited>180)throw Error(`Shot ${i+1} timed out.`);p=await poll(prediction.id);j.progress=Math.min(88,j.progress+1);await save(d);}if(p.status!=='succeeded')throw Error(p.error||`Shot ${i+1} failed.`);const u=outputUrl(p);if(!u)throw Error(`Shot ${i+1} returned no video.`);const f=path.join(PUBLIC,`${id}-shot-${i+1}.mp4`);await download(u,f);shots.push(f);j.progress=10+Math.floor(((i+1)/j.images.length)*75);await save(d);}j.status='merging';j.progress=94;await save(d);const final=path.join(PUBLIC,`${id}.mp4`);await runFfmpeg(shots,final);for(const f of shots)await fs.rm(f,{force:true});j.status='succeeded';j.progress=100;j.output=`/generated/${id}.mp4`;await save(d);}catch(e){j.status='failed';j.error=e.message;j.progress=100;for(const f of shots)await fs.rm(f,{force:true}).catch(()=>{});const w=d.users[j.clientId];if(w&&!j.refunded){w.credits=Math.min(w.plan==='pro'?Number(process.env.PRO_DAILY_CREDITS||100):FREE,w.credits+1);j.refunded=true;}await save(d);}}
async function generate(r,res){const x=multipart(await body(r),r.headers['content-type']||''),p=String(x.fields.prompt||'').trim(),files=x.files;if(p.length<12)return send(res,400,{error:'Prompt must be at least 12 characters.'});if(!files.length)return send(res,400,{error:'Upload at least one reference image.'});const duration=Math.min(10,Math.max(5,Number(x.fields.duration||5))),per=Math.max(2,Math.round(duration/files.length));const id=crypto.randomUUID();const reserved=await serial(async()=>{const d=await db(),w=wallet(d,cid(r));if(w.credits<1)return{no:true,w:{...w}};w.credits--;d.jobs[id]={id,clientId:cid(r),prompt:p,aspect:x.fields.aspectRatio||'16:9',shotDuration:per,images:files.map(f=>({data:f.buffer.toString('base64'),mime:f.mime})),providerIds:[],shot:0,status:'preparing',progress:3,refunded:false,createdAt:new Date().toISOString()};await save(d);return{w:{...w}};});if(reserved.no)return send(res,402,{error:'Daily free credits exhausted.',wallet:reserved.w});runJob(id);return send(res,200,{jobId:id,job:{status:'preparing',progress:3,referenceCount:files.length,mode:'multi-shot-sequence'},wallet:reserved.w});}
async function api(r,res,u){if(r.method==='OPTIONS')return send(res,204,{});if(u.pathname==='/api/health')return send(res,200,{ok:true,provider:'replicate',model:MODEL,configured:Boolean(process.env.REPLICATE_API_TOKEN),multiImageSupport:true,multiImageMode:'independent-shots-ffmpeg-merge'});if(u.pathname==='/api/credits'){const w=await serial(async()=>{const d=await db(),x=wallet(d,cid(r));await save(d);return{...x};});return send(res,200,{...w,dailyCredits:w.plan==='pro'?Number(process.env.PRO_DAILY_CREDITS||100):FREE});}if(u.pathname==='/api/settings'&&r.method==='GET')return send(res,200,{setupEnabled:false,replicateConfigured:Boolean(process.env.REPLICATE_API_TOKEN),replicateTokenPreview:process.env.REPLICATE_API_TOKEN?'r8_••••':'',model:MODEL,upgradeConfigured:Boolean(process.env.UPGRADE_ACCESS_CODE),proDailyCredits:Number(process.env.PRO_DAILY_CREDITS||100)});if(u.pathname==='/api/upgrade'&&r.method==='POST'){const b=JSON.parse((await body(r)).toString()||'{}');if(!process.env.UPGRADE_ACCESS_CODE)return send(res,501,{error:'Upgrade code is not configured.'});if(b.code!==process.env.UPGRADE_ACCESS_CODE)return send(res,403,{error:'Invalid upgrade code.'});const w=await serial(async()=>{const d=await db(),x=wallet(d,cid(r));x.plan='pro';x.credits=Math.max(x.credits,Number(process.env.PRO_DAILY_CREDITS||100));await save(d);return{...x};});return send(res,200,{...w,dailyCredits:Number(process.env.PRO_DAILY_CREDITS||100)});}if(u.pathname==='/api/generate-video'&&r.method==='POST')return generate(r,res);const m=u.pathname.match(/^\/api\/jobs\/([^/]+)$/);if(m){const d=await db(),j=d.jobs[m[1]];if(!j)return send(res,404,{error:'Job not found.'});return send(res,200,{job:{id:j.id,status:j.status,progress:j.progress,shot:j.shot,totalShots:j.images.length,error:j.error,output:j.output},prediction:{status:j.status,output:j.output,error:j.error}});}return send(res,404,{error:'Not found'});}
async function main(r,res){const u=new URL(r.url,`http://${r.headers.host}`);if(u.pathname.startsWith('/generated/')){try{const f=path.join(PUBLIC,path.basename(u.pathname));const b=await fs.readFile(f);return send(res,200,b,'video/mp4');}catch{return send(res,404,'Not found','text/plain');}}if(u.pathname.startsWith('/api/'))return api(r,res,u);const file=path.join(ROOT,u.pathname==='/'?'index.html':u.pathname);try{return send(res,200,await fs.readFile(file),path.extname(file)==='.html'?'text/html; charset=utf-8':path.extname(file)==='.css'?'text/css; charset=utf-8':'text/javascript; charset=utf-8');}catch{return send(res,404,'Not found','text/plain');}}
await fs.mkdir(PUBLIC,{recursive:true});http.createServer((r,s)=>main(r,s).catch(e=>send(s,500,{error:e.message}))).listen(PORT,()=>console.log(`AI video maker running on ${PORT}`));
