const API=location.origin;
const clientId=localStorage.getItem('clientId')||crypto.randomUUID();localStorage.setItem('clientId',clientId);
const state={wallet:null,settings:null,files:[],job:null,busy:false,error:'',mode:'text',prompt:'',negativePrompt:'',progress:0,enhancing:false};
const app=document.getElementById('app');
const samplePrompt='Cinematic ultra-realistic product launch video, smooth dolly movement, dramatic lighting, premium color grade, 4K detail';
const sampleNegative='low quality, blurry, warped faces, flicker, text artifacts';
const esc=v=>String(v).replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'})[c]);
const statusProgress=s=>({starting:8,created:12,queued:20,processing:38,running:55,succeeded:100,failed:100,canceled:100})[s]??Math.max(5,state.progress||5);
const statusText=s=>({starting:'Starting…',created:'Queued…',queued:'Queued…',processing:'Rendering…',running:'Rendering…',succeeded:'Completed',failed:'Generation failed',canceled:'Canceled'})[s]||'Processing…';
function remember(form){if(!form)return;const p=form.elements.prompt?.value,n=form.elements.negativePrompt?.value;if(p!=null)state.prompt=p;if(n!=null)state.negativePrompt=n;}
function battery(pct){const bars=10,filled=Math.round(pct/10);return `<div class="battery-progress"><div class="battery-shell"><div class="battery-fill" style="width:${pct}%"></div><div class="battery-bars">${Array.from({length:bars},(_,i)=>`<i class="${i<filled?'on':''}"></i>`).join('')}</div></div><div class="battery-tip"></div><strong>${pct}%</strong></div>`;}
function render(){const out=Array.isArray(state.job?.prediction?.output)?state.job.prediction.output[0]:state.job?.prediction?.output,s=state.job?.prediction?.status,pct=Math.min(100,Math.max(0,state.progress||statusProgress(s))),done=['succeeded','failed','canceled'].includes(s),plans=state.settings?.paymentPlans||{};
app.innerHTML=`<section class="hero"><div><p class="eyebrow">✦ Real AI video generation</p><h1>Ultimate AI Video Maker</h1><p>Text prompts aur multi-image references se cinematic videos generate karein. Free users ko roz 8 videos milti hain.</p></div><div class="credit"><b>⚡</b><span>${state.wallet?.credits??'—'}</span><small>/ ${state.wallet?.dailyCredits??8} ${state.wallet?.plan??'free'} credits</small></div></section>
<form class="studio" id="studio"><div class="panel wide"><label>Production prompt</label><textarea name="prompt" minlength="12">${esc(state.prompt||samplePrompt)}</textarea><div class="prompt-actions"><button type="button" id="enhance" ${state.enhancing?'disabled':''}>${state.enhancing?'✨ Enhancing…':'✨ Enhance script & prompt'}</button></div><label>Accuracy guard / negative prompt</label><input name="negativePrompt" value="${esc(state.negativePrompt||sampleNegative)}"/></div>
<div class="panel"><label>Generation mode</label><div class="tabs"><button type="button" data-mode="text" class="${state.mode==='text'?'active':''}">Text video</button><button type="button" data-mode="image" class="${state.mode==='image'?'active':''}">Image reference</button></div><input type="hidden" name="mode" value="${state.mode}"/><label>Reference images</label><div class="drop">▧<input id="refs" type="file" accept="image/*" multiple/><span>Upload up to 6 images</span></div><div class="thumbs">${state.files.map((f,i)=>`<img src="${URL.createObjectURL(f)}" alt="Reference ${i+1}"/>`).join('')}</div></div>
<div class="panel controls"><label>Duration</label><select name="duration"><option>5</option><option>10</option></select><label>Aspect ratio</label><select name="aspectRatio"><option>16:9</option><option>9:16</option><option>1:1</option></select><button class="generate" ${state.busy?'disabled':''}>${state.busy?'⏳ Rendering...':'🎬 Generate real video'}</button></div></form>
${state.job?`<section class="result"><h2>Generation status: ${esc(statusText(s))}</h2>${!done?`${battery(pct)}<p class="progress-note">Provider status: ${esc(s||'starting')} · auto-refreshing…</p>`:''}${out?`<video controls src="${esc(out)}"></video>`:s==='failed'?'<p>Generation failed. Credit will be refunded when the failed status is confirmed.</p>':s==='canceled'?'<p>Generation canceled. Credit refunded.</p>':'<p>Rendering in progress. This panel auto-refreshes every few seconds.</p>'}</section>`:''}
<section class="setup panel"><h2>Connect API from phone/browser</h2><p>Status: ${state.settings?.replicateConfigured?`Connected (${esc(state.settings.replicateTokenPreview)})`:'Not connected'} · Browser setup: ${state.settings?.setupEnabled?'Enabled':'Disabled'}</p><form id="settings"><input name="replicateToken" placeholder="Replicate API token: r8_..." autocomplete="off"/><input name="adminPin" placeholder="Admin PIN, if configured" autocomplete="off"/><input name="model" placeholder="Model slug, optional" value="${esc(state.settings?.model||'')}"/><input name="version" placeholder="Replicate version ID, optional" value="${esc(state.settings?.version||'')}"/><button type="submit">Save API</button></form></section>
<section class="upgrade panel"><h2>🚀 Upgrade & unlock more videos</h2><p>Payment ya access code — dono options available.</p><div class="plans">${Object.entries(plans).map(([key,p])=>`<button type="button" class="plan" data-plan="${key}"><b>${esc(p.label)}</b><span>₹${Math.round(Number(p.amount)/100)}</span></button>`).join('')}</div><div class="code-upgrade"><input id="upgradeCode" placeholder="Access / upgrade code"/><button id="upgradeBtn" type="button">Use code</button></div><p class="payment-note">Secure checkout opens after you select a plan. Your secret payment key stays on the server.</p></section>
${state.error?`<div class="error">${esc(state.error)}</div>`:''}`;bind();}
function bind(){const studio=document.getElementById('studio');document.getElementById('refs').addEventListener('change',e=>{remember(studio);state.files=[...e.target.files].slice(0,6);render();});document.querySelectorAll('[data-mode]').forEach(b=>b.addEventListener('click',()=>{remember(studio);state.mode=b.dataset.mode;render();}));studio.addEventListener('input',()=>remember(studio));studio.addEventListener('submit',generate);document.getElementById('enhance').addEventListener('click',enhance);document.getElementById('settings').addEventListener('submit',saveSettings);document.querySelectorAll('[data-plan]').forEach(b=>b.addEventListener('click',()=>pay(b.dataset.plan)));document.getElementById('upgradeBtn').addEventListener('click',upgrade);}
async function refresh(){try{const[c,s]=await Promise.all([fetch(`${API}/api/credits`,{headers:{'x-client-id':clientId}}),fetch(`${API}/api/settings`)]);state.wallet=await c.json();state.settings=await s.json();render();}catch(e){state.error=e.message;render();}}
async function enhance(){const form=document.getElementById('studio');remember(form);if(!state.prompt.trim())return;state.enhancing=true;render();try{const r=await fetch(`${API}/api/prompt-enhance`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({prompt:state.prompt,mode:state.mode,duration:form.elements.duration.value,aspectRatio:form.elements.aspectRatio.value})}),d=await r.json();if(!r.ok)throw Error(d.error||'Enhancement failed');state.prompt=d.enhanced;}catch(e){state.error=e.message;}state.enhancing=false;render();}
async function generate(e){e.preventDefault();remember(e.currentTarget);state.busy=true;state.error='';state.job=null;state.progress=5;render();const f=new FormData(e.currentTarget);state.files.forEach(x=>f.append('references',x));try{const r=await fetch(`${API}/api/generate-video`,{method:'POST',headers:{'x-client-id':clientId},body:f}),d=await r.json();state.busy=false;if(!r.ok){state.error=d.error||'Generation failed';state.progress=0;}else{state.wallet=d.wallet;state.job=d;state.progress=statusProgress(d.prediction?.status);poll(d.jobId);}}catch(x){state.busy=false;state.progress=0;state.error=x.message;}render();}
async function saveSettings(e){e.preventDefault();const p=Object.fromEntries([...new FormData(e.currentTarget).entries()].filter(([,v])=>String(v).trim()));const r=await fetch(`${API}/api/settings`,{method:'POST',headers:{'content-type':'application/json','x-client-id':clientId},body:JSON.stringify(p)}),d=await r.json();if(!r.ok)state.error=d.error||'Settings save failed';else{state.error='';state.settings=d;}render();}
async function upgrade(){const code=document.getElementById('upgradeCode').value.trim();if(!code)return;const r=await fetch(`${API}/api/upgrade`,{method:'POST',headers:{'content-type':'application/json','x-client-id':clientId},body:JSON.stringify({code})}),d=await r.json();if(!r.ok)state.error=d.error||'Upgrade failed';else{state.error='';state.wallet=d;}render();}
async function pay(plan){state.error='';try{const r=await fetch(`${API}/api/payment/order`,{method:'POST',headers:{'content-type':'application/json','x-client-id':clientId},body:JSON.stringify({plan})}),o=await r.json();if(!r.ok)throw Error(o.error||'Payment order failed');if(!window.Razorpay){await loadRazorpay();}const options={key:o.keyId,amount:o.amount,currency:o.currency,name:'Ultimate AI Video Maker',description:o.label,order_id:o.orderId,handler:async response=>{const v=await fetch(`${API}/api/payment/verify`,{method:'POST',headers:{'content-type':'application/json','x-client-id':clientId},body:JSON.stringify(response)}),d=await v.json();if(!v.ok)state.error=d.error||'Payment verification failed';else state.wallet=d.wallet;render();},theme:{color:'#7c5cff'}};new window.Razorpay(options).open();}catch(e){state.error=e.message;render();}}
function loadRazorpay(){return new Promise((resolve,reject)=>{const s=document.createElement('script');s.src='https://checkout.razorpay.com/v1/checkout.js';s.onload=resolve;s.onerror=()=>reject(Error('Payment checkout could not load.'));document.head.appendChild(s);});}
function poll(id){const t=setInterval(async()=>{try{const r=await fetch(`${API}/api/jobs/${id}`,{headers:{'x-client-id':clientId}}),d=await r.json();if(r.ok||r.status===202){state.job={jobId:id,...d};const s=d.prediction?.status;state.progress=s==='succeeded'?100:s==='failed'||s==='canceled'?100:Math.min(95,Math.max(state.progress+3,statusProgress(s)));if(['succeeded','failed','canceled'].includes(s)){clearInterval(t);state.busy=false;if(s!=='succeeded'){state.error=d.prediction?.error||'Video generation failed. Credit refunded.';await refresh();}}render();}}catch(e){state.error=e.message;render();}},2500);}
render();refresh();
