const API=location.origin;
const clientId=localStorage.getItem('clientId')||crypto.randomUUID();localStorage.setItem('clientId',clientId);
const state={wallet:null,settings:null,files:[],job:null,busy:false,error:'',mode:'text',prompt:'',negativePrompt:'',progress:0,enhancing:false};
const app=document.getElementById('app');
const samplePrompt='Cinematic ultra-realistic product launch video, smooth dolly movement, dramatic lighting, premium color grade, 4K detail';
const sampleNegative='low quality, blurry, warped faces, flicker, text artifacts';
const esc=v=>String(v).replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;','\\':''})[c]);
const statusText=s=>({preparing:'Preparing reference shots…',generating:'Generating shots…',merging:'Merging final video…',succeeded:'Completed',failed:'Generation failed'})[s]||'Processing…';
function remember(form){if(!form)return;const p=form.elements.prompt?.value,n=form.elements.negativePrompt?.value;if(p!=null)state.prompt=p;if(n!=null)state.negativePrompt=n;}
function battery(pct){const p=Math.max(0,Math.min(100,Math.round(pct||0))),bars=10,filled=Math.round(p/10);return `<div class="battery-progress"><div class="battery-shell"><div class="battery-fill" style="width:${p}%"></div><div class="battery-bars">${Array.from({length:bars},(_,i)=>`<i class="${i<filled?'on':''}"></i>`).join('')}</div></div><div class="battery-tip"></div><strong>${p}%</strong></div>`;}
function render(){const j=state.job?.job||state.job,s=state.job?.prediction?.status||j?.status,pct=Number(j?.progress??state.progress??0),done=['succeeded','failed'].includes(s),out=state.job?.prediction?.output||j?.output,plans=state.settings?.paymentPlans||{};
app.innerHTML=`<section class="hero"><div><p class="eyebrow">✦ Real AI video generation</p><h1>Ultimate AI Video Maker</h1><p>Text prompts aur multi-image references se cinematic videos generate karein. Multiple images ab sequential cinematic shots ke roop mein process hoti hain.</p></div><div class="credit"><b>⚡</b><span>${state.wallet?.credits??'—'}</span><small>/ ${state.wallet?.dailyCredits??8} ${state.wallet?.plan??'free'} credits</small></div></section>
<form class="studio" id="studio"><div class="panel wide"><label>Production prompt</label><textarea name="prompt" minlength="12">${esc(state.prompt||samplePrompt)}</textarea><div class="prompt-actions"><button type="button" id="enhance" disabled>✨ Script enhancer (coming next)</button></div><label>Accuracy guard / negative prompt</label><input name="negativePrompt" value="${esc(state.negativePrompt||sampleNegative)}"/></div>
<div class="panel"><label>Generation mode</label><div class="tabs"><button type="button" data-mode="text" class="${state.mode==='text'?'active':''}">Text video</button><button type="button" data-mode="image" class="${state.mode==='image'?'active':''}">Multi-image shots</button></div><input type="hidden" name="mode" value="${state.mode}"/><label>Reference images</label><div class="drop">▧<input id="refs" type="file" accept="image/*" multiple/><span>Upload up to 4 images · each becomes its own cinematic shot</span></div><div class="thumbs">${state.files.map((f,i)=>`<img src="${URL.createObjectURL(f)}" alt="Reference ${i+1}"/>`).join('')}</div>${state.files.length?`<small class="reference-note">${state.files.length} shot${state.files.length>1?'s':''} queued · images are NOT combined into a collage</small>`:''}</div>
<div class="panel controls"><label>Duration</label><select name="duration"><option>5</option><option>10</option></select><label>Aspect ratio</label><select name="aspectRatio"><option>16:9</option><option>9:16</option><option>1:1</option></select><button class="generate" ${state.busy?'disabled':''}>${state.busy?'⏳ Generating...':'🎬 Generate real video'}</button></div></form>
${state.job?`<section class="result"><h2>Generation status: ${esc(statusText(s))}</h2>${battery(pct)}<p class="progress-note">${j?.totalShots?`Shot ${Math.min(j.shot||0,j.totalShots)}/${j.totalShots} · `:''}${s==='merging'?'Combining the finished shots into one MP4…':s==='generating'?'Generating each reference image as a separate video shot…':s==='preparing'?'Preparing your references…':s==='succeeded'?'Final video ready.':'Auto-refreshing job status…'}</p>${out?`<video controls playsinline src="${esc(out)}"></video>`:''}${s==='failed'?`<p class="error">${esc(j?.error||'Generation failed. Any reserved app credit has been refunded.')}</p>`:''}</section>`:''}
<section class="setup panel"><h2>Connect API from phone/browser</h2><p>Status: ${state.settings?.replicateConfigured?`Connected (${esc(state.settings.replicateTokenPreview)})`:'Not connected'} · Browser setup: ${state.settings?.setupEnabled?'Enabled':'Disabled'}</p></section>
<section class="upgrade panel"><h2>🚀 Upgrade & unlock more videos</h2><p>Access code remains available. Online payment can be enabled later without changing the video pipeline.</p><div class="code-upgrade"><input id="upgradeCode" placeholder="Access / upgrade code"/><button id="upgradeBtn" type="button">Use code</button></div></section>
${state.error?`<div class="error">${esc(state.error)}</div>`:''}`;bind();}
function bind(){const studio=document.getElementById('studio');document.getElementById('refs').addEventListener('change',e=>{remember(studio);state.files=[...e.target.files].slice(0,4);if(state.files.length)state.mode='image';render();});document.querySelectorAll('[data-mode]').forEach(b=>b.addEventListener('click',()=>{remember(studio);state.mode=b.dataset.mode;render();}));studio.addEventListener('input',()=>remember(studio));studio.addEventListener('submit',generate);document.getElementById('upgradeBtn').addEventListener('click',upgrade);}
async function refresh(){try{const[c,s]=await Promise.all([fetch(`${API}/api/credits`,{headers:{'x-client-id':clientId}}),fetch(`${API}/api/settings`)]);state.wallet=await c.json();state.settings=await s.json();render();}catch(e){state.error=e.message;render();}}
async function generate(e){e.preventDefault();remember(e.currentTarget);if(!state.files.length){state.error='Please upload at least one reference image.';render();return;}state.busy=true;state.error='';state.job=null;state.progress=3;render();const f=new FormData(e.currentTarget);state.files.forEach(x=>f.append('references',x));try{const r=await fetch(`${API}/api/generate-video`,{method:'POST',headers:{'x-client-id':clientId},body:f}),d=await r.json();if(!r.ok){state.busy=false;state.error=d.error||'Generation failed';state.progress=0;}else{state.wallet=d.wallet;state.job=d;state.progress=d.job?.progress||3;poll(d.jobId);}}catch(x){state.busy=false;state.error=x.message;state.progress=0;}render();}
async function upgrade(){const code=document.getElementById('upgradeCode').value.trim();if(!code)return;const r=await fetch(`${API}/api/upgrade`,{method:'POST',headers:{'content-type':'application/json','x-client-id':clientId},body:JSON.stringify({code})}),d=await r.json();if(!r.ok)state.error=d.error||'Upgrade failed';else{state.error='';state.wallet=d;}render();}
function poll(id){const timer=setInterval(async()=>{try{const r=await fetch(`${API}/api/jobs/${id}`,{headers:{'x-client-id':clientId}}),d=await r.json();if(!r.ok){if(r.status===404){clearInterval(timer);state.busy=false;state.error='Generation job was not found.';render();}return;}state.job={jobId:id,...d};state.progress=Number(d.job?.progress??state.progress);const s=d.job?.status||d.prediction?.status;if(s==='succeeded'||s==='failed'){clearInterval(timer);state.busy=false;if(s==='failed')state.error=d.job?.error||'Generation failed. Credit refunded.';}render();}catch(e){state.error=e.message;render();}},2500);}
render();refresh();