const API = location.origin;
const clientId = localStorage.getItem('clientId') || crypto.randomUUID();
localStorage.setItem('clientId', clientId);

const state = { wallet: null, settings: null, files: [], job: null, busy: false, error: '', mode: 'text', prompt: '', negativePrompt: '', progress: 0 };
const app = document.getElementById('app');
const samplePrompt = 'Cinematic ultra-realistic product launch video, smooth dolly movement, dramatic lighting, premium color grade, 4K detail';
const sampleNegative = 'low quality, blurry, warped faces, flicker, text artifacts';

function escapeHtml(value) { return String(value).replace(/[&<>\"]/g, (char) => ({ '&':'&amp;', '<':'&lt;', '>':'&gt;', '\"':'&quot;' })[char]); }
function rememberFormValues(form) { if (!form) return; const prompt=form.elements.prompt?.value, negativePrompt=form.elements.negativePrompt?.value; if(prompt!=null)state.prompt=prompt; if(negativePrompt!=null)state.negativePrompt=negativePrompt; }
function statusProgress(status){ return ({starting:8,created:10,queued:18,processing:35,running:50,succeeded:100,failed:100,canceled:100})[status] ?? Math.max(5,state.progress||5); }
function statusText(status){ return ({starting:'Starting…',created:'Queued…',queued:'Queued…',processing:'Rendering…',running:'Rendering…',succeeded:'Completed',failed:'Generation failed',canceled:'Canceled'})[status] || 'Processing…'; }

function render() {
  const output = Array.isArray(state.job?.prediction?.output) ? state.job.prediction.output[0] : state.job?.prediction?.output;
  const dailyCredits = state.wallet?.dailyCredits ?? 8;
  const prompt = state.prompt || samplePrompt;
  const negativePrompt = state.negativePrompt || sampleNegative;
  const status = state.job?.prediction?.status;
  const pct = Math.min(100, Math.max(0, state.progress || statusProgress(status)));
  const isDone = ['succeeded','failed','canceled'].includes(status);
  app.innerHTML = `
    <section class="hero"><div><p class="eyebrow">✦ Real AI video generation</p><h1>Ultimate AI Video Maker</h1><p>Text prompts aur multi-image references se fast, sharp, provider-backed cinematic videos generate karein. Free users ko roz 8 videos milti hain; 00:00 UTC par credits refresh ho jaate hain.</p></div><div class="credit"><b>⚡</b><span>${state.wallet?.credits ?? '—'}</span><small>/ ${dailyCredits} ${state.wallet?.plan ?? 'free'} credits today</small></div></section>
    <form class="studio" id="studio"><div class="panel wide"><label>Production prompt</label><textarea name="prompt" minlength="12">${escapeHtml(prompt)}</textarea><label>Accuracy guard / negative prompt</label><input name="negativePrompt" value="${escapeHtml(negativePrompt)}" /></div>
    <div class="panel"><label>Generation mode</label><div class="tabs"><button type="button" data-mode="text" class="${state.mode==='text'?'active':''}">Text video</button><button type="button" data-mode="image" class="${state.mode==='image'?'active':''}">Image reference</button></div><input type="hidden" name="mode" value="${state.mode}"/><label>Reference images</label><div class="drop">▧<input id="refs" type="file" accept="image/*" multiple/><span>Upload up to 6 images</span></div><div class="thumbs">${state.files.map((file,i)=>`<img src="${URL.createObjectURL(file)}" alt="Reference ${i+1}"/>`).join('')}</div></div>
    <div class="panel controls"><label>Duration</label><select name="duration"><option>5</option><option>10</option></select><label>Aspect ratio</label><select name="aspectRatio"><option>16:9</option><option>9:16</option><option>1:1</option></select><button class="generate" ${state.busy?'disabled':''}>${state.busy?'⏳ Rendering...':'🎬 Generate real video'}</button></div></form>
    <section class="setup panel"><h2>Connect API from phone/browser</h2><p>Status: ${state.settings?.replicateConfigured?`Connected (${escapeHtml(state.settings.replicateTokenPreview)})`:'Not connected'} · Browser setup: ${state.settings?.setupEnabled?'Enabled':'Disabled'}</p><form id="settings"><input name="replicateToken" placeholder="Replicate API token: r8_..." autocomplete="off"/><input name="adminPin" placeholder="Admin PIN, if configured" autocomplete="off"/><input name="model" placeholder="Model slug, optional" value="${escapeHtml(state.settings?.model||'')}"/><input name="version" placeholder="Replicate version ID, optional" value="${escapeHtml(state.settings?.version||'')}"/><button type="submit">Save API</button></form></section>
    <section class="upgrade panel"><h2>Need more than 8 videos?</h2><p>Upgrade code daalein aur pro daily credits unlock karein. Agar upgrade configured nahi hai, app clearly bata dega.</p><form id="upgrade"><input name="code" placeholder="Upgrade access code"/><button type="submit">Upgrade</button></form></section>
    ${state.error?`<div class="error">${escapeHtml(state.error)}</div>`:''}
    ${state.job?`<section class="result"><h2>Generation status: ${escapeHtml(statusText(status))}</h2>${!isDone?`<div class="progress-wrap"><div class="progress-top"><span>Generating video</span><strong>${pct}%</strong></div><div class="progress-bar"><div class="progress-fill" style="width:${pct}%"></div></div><p class="progress-note">Provider status: ${escapeHtml(status||'starting')} · auto-refreshing…</p></div>`:''}${output?`<video controls src="${escapeHtml(output)}"></video>`:status==='failed'?`<p>Generation failed. Your app credit has been refunded automatically (when the provider reports a failed job).</p>`:status==='canceled'?`<p>Generation was canceled. Your app credit has been refunded.</p>`:'<p>Rendering in progress. This panel auto-refreshes every few seconds.</p>'}</section>`:''}`;
  bind();
}

function bind(){const studio=document.getElementById('studio');document.getElementById('refs').addEventListener('change',(event)=>{rememberFormValues(studio);state.files=[...event.target.files].slice(0,6);render();});document.querySelectorAll('[data-mode]').forEach(button=>button.addEventListener('click',()=>{rememberFormValues(studio);state.mode=button.dataset.mode;render();}));studio.addEventListener('input',()=>rememberFormValues(studio));studio.addEventListener('submit',generate);document.getElementById('settings').addEventListener('submit',saveSettings);document.getElementById('upgrade').addEventListener('submit',upgrade);}
async function refreshCredits(){const [creditsRes,settingsRes]=await Promise.all([fetch(`${API}/api/credits`,{headers:{'x-client-id':clientId}}),fetch(`${API}/api/settings`,{headers:{'x-client-id':clientId}})]);state.wallet=await creditsRes.json();state.settings=await settingsRes.json();render();}
async function generate(event){event.preventDefault();rememberFormValues(event.currentTarget);state.busy=true;state.error='';state.job=null;state.progress=5;render();const form=new FormData(event.currentTarget);state.files.forEach(file=>form.append('references',file));try{const res=await fetch(`${API}/api/generate-video`,{method:'POST',headers:{'x-client-id':clientId},body:form});const data=await res.json();state.busy=false;if(!res.ok){state.error=data.error||'Generation failed';state.progress=0;}else{state.wallet=data.wallet;state.job=data;state.progress=statusProgress(data.prediction?.status);pollJob(data.jobId);} }catch(error){state.busy=false;state.progress=0;state.error=error.message||'Network error while generating video';}render();}
async function saveSettings(event){event.preventDefault();const form=new FormData(event.currentTarget);const payload=Object.fromEntries([...form.entries()].filter(([,value])=>String(value).trim()));const res=await fetch(`${API}/api/settings`,{method:'POST',headers:{'content-type':'application/json','x-client-id':clientId},body:JSON.stringify(payload)});const data=await res.json();if(!res.ok)state.error=data.error||'Settings save failed';else{state.error='';state.settings=data;}render();}
async function upgrade(event){event.preventDefault();const code=new FormData(event.currentTarget).get('code');const res=await fetch(`${API}/api/upgrade`,{method:'POST',headers:{'content-type':'application/json','x-client-id':clientId},body:JSON.stringify({code})});const data=await res.json();if(!res.ok)state.error=data.error||'Upgrade failed';else{state.error='';state.wallet=data;}render();}
function pollJob(jobId){const timer=setInterval(async()=>{try{const res=await fetch(`${API}/api/jobs/${jobId}`,{headers:{'x-client-id':clientId}});const data=await res.json();if(res.ok||res.status===202){state.job={jobId,...data};const s=data.prediction?.status;state.progress=s==='succeeded'?100:s==='failed'||s==='canceled'?100:Math.min(95,Math.max(state.progress+3,statusProgress(s)));if(['succeeded','failed','canceled'].includes(s)){clearInterval(timer);state.busy=false;if(s!=='succeeded'){state.error=data.prediction?.error||'Video generation failed. Credit refunded.';await refreshCredits();}}render();}}catch(error){state.error=error.message||'Could not check generation status.';render();}},2500);}
render();refreshCredits();
